2024-06-04 18:08:34,692 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:08:34,693 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:08:34,693 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:08:40,444 - websockets.server - INFO - connection open
2024-06-04 18:08:40,446 - __main__ - INFO - Received: 1
2024-06-04 18:08:40,446 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:08:40,451 - websockets.server - INFO - connection closed
2024-06-04 18:08:45,882 - websockets.server - INFO - connection open
2024-06-04 18:08:45,886 - __main__ - INFO - Received: 2
2024-06-04 18:08:45,886 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:08:45,894 - websockets.server - INFO - connection closed
2024-06-04 18:09:16,551 - websockets.server - INFO - connection open
2024-06-04 18:09:16,553 - __main__ - INFO - Received: 1
2024-06-04 18:09:16,553 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:09:16,557 - websockets.server - INFO - connection closed
2024-06-04 18:09:19,556 - websockets.server - INFO - connection open
2024-06-04 18:09:19,560 - __main__ - INFO - Received: 2
2024-06-04 18:09:19,560 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:09:19,569 - websockets.server - INFO - connection closed
2024-06-04 18:09:22,654 - websockets.server - INFO - connection open
2024-06-04 18:09:22,656 - __main__ - INFO - Received: 1
2024-06-04 18:09:22,656 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:09:22,660 - websockets.server - INFO - connection closed
2024-06-04 18:10:56,781 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:10:56,782 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:10:56,782 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:11:20,358 - websockets.server - INFO - connection open
2024-06-04 18:11:20,360 - __main__ - INFO - Received: 2
2024-06-04 18:11:20,360 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:11:21,365 - websockets.server - INFO - connection closed
2024-06-04 18:11:23,560 - websockets.server - INFO - connection open
2024-06-04 18:11:23,561 - __main__ - INFO - Received: 1
2024-06-04 18:11:23,562 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:11:24,567 - websockets.server - INFO - connection closed
2024-06-04 18:12:47,356 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:12:47,357 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:12:47,357 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:12:51,965 - websockets.server - INFO - connection open
2024-06-04 18:12:51,967 - __main__ - INFO - Received: 1
2024-06-04 18:12:51,968 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:12:52,972 - websockets.server - INFO - connection closed
2024-06-04 18:12:54,567 - websockets.server - INFO - connection open
2024-06-04 18:12:54,569 - __main__ - INFO - Received: 2
2024-06-04 18:12:54,569 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:12:55,579 - websockets.server - INFO - connection closed
2024-06-04 18:12:59,969 - websockets.server - INFO - connection open
2024-06-04 18:12:59,971 - __main__ - INFO - Received: 2
2024-06-04 18:12:59,971 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:13:00,980 - websockets.server - INFO - connection closed
2024-06-04 18:13:06,171 - websockets.server - INFO - connection open
2024-06-04 18:13:06,173 - __main__ - INFO - Received: 2
2024-06-04 18:13:06,173 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:13:07,181 - websockets.server - INFO - connection closed
2024-06-04 18:13:26,274 - websockets.server - INFO - connection open
2024-06-04 18:13:26,276 - __main__ - INFO - Received: 1
2024-06-04 18:13:26,276 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:13:27,280 - websockets.server - INFO - connection closed
2024-06-04 18:13:28,477 - websockets.server - INFO - connection open
2024-06-04 18:13:28,479 - __main__ - INFO - Received: 2
2024-06-04 18:13:28,479 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:13:29,483 - websockets.server - INFO - connection closed
2024-06-04 18:14:42,548 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 18:14:42,548 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 18:14:42,549 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 18:14:48,084 - websockets.server - INFO - connection open
2024-06-04 18:14:48,086 - __main__ - INFO - Received: 1
2024-06-04 18:14:48,086 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 18:14:49,095 - websockets.server - INFO - connection closed
2024-06-04 18:14:50,483 - websockets.server - INFO - connection open
2024-06-04 18:14:50,485 - __main__ - INFO - Received: 2
2024-06-04 18:14:50,485 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 18:14:51,490 - websockets.server - INFO - connection closed
2024-06-04 19:25:37,833 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 19:25:37,833 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 19:25:37,833 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 19:26:05,341 - websockets.server - INFO - connection open
2024-06-04 19:26:05,342 - __main__ - INFO - Received: 1
2024-06-04 19:26:05,342 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 19:26:06,346 - websockets.server - INFO - connection closed
2024-06-04 19:26:08,339 - websockets.server - INFO - connection open
2024-06-04 19:26:08,341 - __main__ - INFO - Received: 2
2024-06-04 19:26:08,341 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 19:26:09,345 - websockets.server - INFO - connection closed
2024-06-04 21:37:23,470 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:37:23,471 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:37:23,471 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:37:36,776 - websockets.server - INFO - connection open
2024-06-04 21:37:36,781 - __main__ - INFO - Received: 6
2024-06-04 21:37:36,781 - __main__ - INFO - Inicia la clase
2024-06-04 21:37:36,798 - websockets.server - INFO - connection closed
2024-06-04 21:37:39,450 - websockets.server - INFO - connection open
2024-06-04 21:37:39,452 - __main__ - INFO - Received: 1
2024-06-04 21:37:39,452 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:37:40,456 - websockets.server - INFO - connection closed
2024-06-04 21:37:42,558 - websockets.server - INFO - connection open
2024-06-04 21:37:42,563 - __main__ - INFO - Received: 2
2024-06-04 21:37:42,563 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:37:43,572 - websockets.server - INFO - connection closed
2024-06-04 21:37:46,657 - websockets.server - INFO - connection open
2024-06-04 21:37:46,659 - __main__ - INFO - Received: 7
2024-06-04 21:37:46,659 - __main__ - INFO - Finaliza la clase
2024-06-04 21:37:46,661 - websockets.server - INFO - connection closed
2024-06-04 21:40:31,681 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:40:31,681 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:40:31,681 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:40:42,469 - websockets.server - INFO - connection open
2024-06-04 21:40:42,472 - __main__ - INFO - Received: 6
2024-06-04 21:40:42,472 - __main__ - INFO - Inicia la clase
2024-06-04 21:40:47,663 - websockets.server - INFO - connection open
2024-06-04 21:40:47,665 - __main__ - INFO - Received: 1
2024-06-04 21:40:47,665 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:40:53,364 - websockets.server - INFO - connection open
2024-06-04 21:40:53,366 - __main__ - INFO - Received: 2
2024-06-04 21:40:53,366 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:40:57,066 - websockets.server - INFO - connection open
2024-06-04 21:40:57,068 - __main__ - INFO - Received: 7
2024-06-04 21:40:57,068 - __main__ - INFO - Finaliza la clase
2024-06-04 21:40:57,073 - websockets.server - INFO - connection closed
2024-06-04 21:41:02,970 - websockets.server - INFO - connection open
2024-06-04 21:41:02,972 - __main__ - INFO - Received: 7
2024-06-04 21:41:02,972 - __main__ - INFO - Finaliza la clase
2024-06-04 21:41:02,977 - websockets.server - INFO - connection closed
2024-06-04 21:41:43,099 - websockets.server - INFO - connection closed
2024-06-04 21:41:43,099 - websockets.server - INFO - connection closed
2024-06-04 21:41:43,100 - websockets.server - INFO - connection closed
2024-06-04 21:41:57,087 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:41:57,087 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:41:57,088 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:42:03,274 - websockets.server - INFO - connection open
2024-06-04 21:42:03,276 - __main__ - INFO - Received: 6
2024-06-04 21:42:03,276 - __main__ - INFO - Inicia la clase
2024-06-04 21:42:05,383 - websockets.server - INFO - connection open
2024-06-04 21:42:05,385 - __main__ - INFO - Received: 1
2024-06-04 21:42:05,385 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:42:09,277 - websockets.server - INFO - connection open
2024-06-04 21:42:09,279 - __main__ - INFO - Received: 7
2024-06-04 21:42:09,279 - __main__ - INFO - Finaliza la clase
2024-06-04 21:42:09,282 - websockets.server - INFO - connection closed
2024-06-04 21:43:32,225 - websockets.server - INFO - connection closed
2024-06-04 21:43:32,225 - websockets.server - INFO - connection closed
2024-06-04 21:43:51,210 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:43:51,211 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:43:51,211 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:44:02,192 - websockets.server - INFO - connection open
2024-06-04 21:44:02,194 - __main__ - INFO - Received: 6
2024-06-04 21:44:02,195 - __main__ - INFO - Inicia la clase
2024-06-04 21:44:07,085 - websockets.server - INFO - connection open
2024-06-04 21:44:07,086 - __main__ - INFO - Received: 1
2024-06-04 21:44:07,087 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:44:09,987 - websockets.server - INFO - connection open
2024-06-04 21:44:09,989 - __main__ - INFO - Received: 2
2024-06-04 21:44:09,989 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:44:13,893 - websockets.server - INFO - connection open
2024-06-04 21:44:13,895 - __main__ - INFO - Received: 7
2024-06-04 21:44:13,896 - __main__ - INFO - Finaliza la clase
2024-06-04 21:44:13,900 - websockets.server - INFO - connection closed
2024-06-04 21:45:30,329 - websockets.server - INFO - connection closed
2024-06-04 21:45:30,329 - websockets.server - INFO - connection closed
2024-06-04 21:45:30,330 - websockets.server - INFO - connection closed
2024-06-04 21:46:51,256 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:46:51,257 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:46:51,257 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:47:02,705 - websockets.server - INFO - connection open
2024-06-04 21:47:02,707 - __main__ - INFO - Received: 6
2024-06-04 21:47:02,708 - __main__ - INFO - Inicia la clase
2024-06-04 21:47:07,597 - websockets.server - INFO - connection open
2024-06-04 21:47:07,599 - __main__ - INFO - Received: 1
2024-06-04 21:47:07,599 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:47:15,804 - websockets.server - INFO - connection open
2024-06-04 21:47:15,806 - __main__ - INFO - Received: 2
2024-06-04 21:47:15,806 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:47:19,605 - websockets.server - INFO - connection open
2024-06-04 21:47:19,607 - __main__ - INFO - Received: 7
2024-06-04 21:47:19,608 - __main__ - INFO - Finaliza la clase
2024-06-04 21:47:19,613 - websockets.server - INFO - connection closed
2024-06-04 21:47:25,803 - websockets.server - INFO - connection open
2024-06-04 21:47:25,805 - __main__ - INFO - Received: 6
2024-06-04 21:47:25,805 - __main__ - INFO - Inicia la clase
2024-06-04 21:47:30,506 - websockets.server - INFO - connection open
2024-06-04 21:47:30,508 - __main__ - INFO - Received: 7
2024-06-04 21:47:30,509 - __main__ - INFO - Finaliza la clase
2024-06-04 21:47:30,514 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,086 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,087 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,087 - websockets.server - INFO - connection closed
2024-06-04 21:47:35,087 - websockets.server - INFO - connection closed
2024-06-04 21:49:29,375 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:49:29,375 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:49:29,375 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:49:36,609 - websockets.server - INFO - connection open
2024-06-04 21:49:36,610 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    while is_running:
          ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'is_running' where it is not associated with a value
2024-06-04 21:49:36,612 - websockets.server - INFO - connection closed
2024-06-04 21:49:51,324 - websockets.server - INFO - connection open
2024-06-04 21:49:51,324 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    while is_running:
          ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'is_running' where it is not associated with a value
2024-06-04 21:49:51,326 - websockets.server - INFO - connection closed
2024-06-04 21:50:15,925 - websockets.server - INFO - connection open
2024-06-04 21:50:15,926 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    while is_running:
          ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'is_running' where it is not associated with a value
2024-06-04 21:50:15,928 - websockets.server - INFO - connection closed
2024-06-04 21:51:32,664 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:51:32,664 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:51:32,664 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:51:41,628 - websockets.server - INFO - connection open
2024-06-04 21:51:41,631 - __main__ - INFO - Received: 6
2024-06-04 21:51:41,631 - __main__ - INFO - Inicia la clase
2024-06-04 21:51:41,638 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:51:41,641 - websockets.server - INFO - connection closed
2024-06-04 21:51:45,225 - websockets.server - INFO - connection open
2024-06-04 21:51:45,227 - __main__ - INFO - Received: 1
2024-06-04 21:51:45,227 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:51:46,231 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:51:46,233 - websockets.server - INFO - connection closed
2024-06-04 21:51:50,026 - websockets.server - INFO - connection open
2024-06-04 21:51:50,029 - __main__ - INFO - Received: 7
2024-06-04 21:51:50,029 - __main__ - INFO - Finaliza la clase
2024-06-04 21:51:50,034 - websockets.server - INFO - connection closed
2024-06-04 21:51:56,631 - websockets.server - INFO - connection open
2024-06-04 21:51:56,632 - __main__ - INFO - Received: 7
2024-06-04 21:51:56,632 - __main__ - INFO - Finaliza la clase
2024-06-04 21:51:56,636 - websockets.server - INFO - connection closed
2024-06-04 21:52:03,729 - websockets.server - INFO - connection open
2024-06-04 21:52:03,731 - __main__ - INFO - Received: 1
2024-06-04 21:52:03,731 - __main__ - INFO - Ejecutando script pizarra 1
2024-06-04 21:52:04,737 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:52:04,739 - websockets.server - INFO - connection closed
2024-06-04 21:52:06,428 - websockets.server - INFO - connection open
2024-06-04 21:52:06,430 - __main__ - INFO - Received: 2
2024-06-04 21:52:06,430 - __main__ - INFO - Ejecutando script pizarra 2
2024-06-04 21:52:07,434 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Wait for a message
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:52:07,436 - websockets.server - INFO - connection closed
2024-06-04 21:53:38,442 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 21:53:38,442 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 21:53:38,443 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 21:53:44,733 - websockets.server - INFO - connection open
2024-06-04 21:53:44,735 - __main__ - INFO - Recibido: 6
2024-06-04 21:53:44,735 - __main__ - INFO - Iniciando la clase
2024-06-04 21:53:44,742 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:44,746 - websockets.server - INFO - connection closed
2024-06-04 21:53:49,934 - websockets.server - INFO - connection open
2024-06-04 21:53:49,936 - __main__ - INFO - Recibido: 1
2024-06-04 21:53:49,936 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 21:53:50,941 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:50,942 - websockets.server - INFO - connection closed
2024-06-04 21:53:53,137 - websockets.server - INFO - connection open
2024-06-04 21:53:53,139 - __main__ - INFO - Recibido: 1
2024-06-04 21:53:53,139 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 21:53:54,143 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:54,145 - websockets.server - INFO - connection closed
2024-06-04 21:53:56,138 - websockets.server - INFO - connection open
2024-06-04 21:53:56,140 - __main__ - INFO - Recibido: 2
2024-06-04 21:53:56,140 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-04 21:53:57,144 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 21:53:57,145 - websockets.server - INFO - connection closed
2024-06-04 21:54:00,842 - websockets.server - INFO - connection open
2024-06-04 21:54:00,844 - __main__ - INFO - Recibido: 7
2024-06-04 21:54:00,844 - __main__ - INFO - Finalizando la clase
2024-06-04 21:54:00,847 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 47, in handle_client
    await websocket.send(response)
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2024-06-04 21:54:00,849 - websockets.server - INFO - connection closed
2024-06-04 22:17:25,071 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-04 22:17:25,071 - websockets.server - INFO - server listening on [::1]:8766
2024-06-04 22:17:25,071 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-04 22:17:38,372 - websockets.server - INFO - connection open
2024-06-04 22:17:38,373 - __main__ - INFO - Recibido: 1
2024-06-04 22:17:38,374 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 22:17:39,378 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 22:17:39,381 - websockets.server - INFO - connection closed
2024-06-04 22:17:41,381 - websockets.server - INFO - connection open
2024-06-04 22:17:41,382 - __main__ - INFO - Recibido: 2
2024-06-04 22:17:41,383 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-04 22:17:42,387 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 22:17:42,388 - websockets.server - INFO - connection closed
2024-06-04 22:17:44,974 - websockets.server - INFO - connection open
2024-06-04 22:17:44,976 - __main__ - INFO - Recibido: 1
2024-06-04 22:17:44,976 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-04 22:17:45,982 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-04 22:17:45,984 - websockets.server - INFO - connection closed
2024-06-05 17:21:55,311 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 17:21:55,312 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 17:21:55,312 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 17:22:07,912 - websockets.server - INFO - connection open
2024-06-05 17:22:07,914 - __main__ - INFO - Recibido: 1
2024-06-05 17:22:07,914 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 17:22:08,920 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 17:22:08,929 - websockets.server - INFO - connection closed
2024-06-05 17:22:10,803 - websockets.server - INFO - connection open
2024-06-05 17:22:10,805 - __main__ - INFO - Recibido: 2
2024-06-05 17:22:10,805 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-05 17:22:11,810 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 17:22:11,811 - websockets.server - INFO - connection closed
2024-06-05 17:22:14,002 - websockets.server - INFO - connection open
2024-06-05 17:22:14,004 - __main__ - INFO - Recibido: 1
2024-06-05 17:22:14,004 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 17:22:15,008 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 14, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 17:22:15,010 - websockets.server - INFO - connection closed
2024-06-05 19:34:46,198 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 19:34:46,198 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 19:34:46,198 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 19:38:10,896 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 19:38:10,897 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 19:38:10,897 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 19:40:42,218 - websockets.server - INFO - connection open
2024-06-05 19:40:42,220 - __main__ - INFO - Recibido: 6
2024-06-05 19:40:42,220 - __main__ - INFO - Iniciando la clase
2024-06-05 19:40:42,246 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:40:42,249 - websockets.server - INFO - connection closed
2024-06-05 19:40:50,413 - websockets.server - INFO - connection open
2024-06-05 19:40:50,415 - __main__ - INFO - Recibido: 6
2024-06-05 19:40:50,415 - __main__ - INFO - Iniciando la clase
2024-06-05 19:40:50,430 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:40:50,432 - websockets.server - INFO - connection closed
2024-06-05 19:43:33,816 - websockets.server - INFO - connection open
2024-06-05 19:43:33,818 - __main__ - INFO - Recibido: 6
2024-06-05 19:43:33,818 - __main__ - INFO - Iniciando la clase
2024-06-05 19:43:33,848 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:43:33,850 - websockets.server - INFO - connection closed
2024-06-05 19:46:01,732 - websockets.server - INFO - connection open
2024-06-05 19:46:01,735 - __main__ - INFO - Recibido: 6
2024-06-05 19:46:01,736 - __main__ - INFO - Iniciando la clase
2024-06-05 19:46:01,743 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7c928590>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5080): Max retries exceeded with url: /log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c928590>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 45, in handle_client
    requests.get(url, json=data)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5080): Max retries exceeded with url: /log (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c928590>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-05 19:46:01,768 - websockets.server - INFO - connection closed
2024-06-05 19:48:49,907 - websockets.server - INFO - connection open
2024-06-05 19:48:49,909 - __main__ - INFO - Recibido: 6
2024-06-05 19:48:49,909 - __main__ - INFO - Iniciando la clase
2024-06-05 19:48:49,940 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:48:49,941 - websockets.server - INFO - connection closed
2024-06-05 19:50:04,800 - websockets.server - INFO - connection open
2024-06-05 19:50:04,802 - __main__ - INFO - Recibido: 1
2024-06-05 19:50:04,802 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:50:05,806 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:50:05,807 - websockets.server - INFO - connection closed
2024-06-05 19:50:07,102 - websockets.server - INFO - connection open
2024-06-05 19:50:07,104 - __main__ - INFO - Recibido: 6
2024-06-05 19:50:07,104 - __main__ - INFO - Iniciando la clase
2024-06-05 19:50:07,121 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:50:07,123 - websockets.server - INFO - connection closed
2024-06-05 19:50:57,509 - websockets.server - INFO - connection open
2024-06-05 19:50:57,511 - __main__ - INFO - Recibido: 6
2024-06-05 19:50:57,511 - __main__ - INFO - Iniciando la clase
2024-06-05 19:50:57,526 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:50:57,528 - websockets.server - INFO - connection closed
2024-06-05 19:51:01,708 - websockets.server - INFO - connection open
2024-06-05 19:51:01,710 - __main__ - INFO - Recibido: 1
2024-06-05 19:51:01,710 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:51:02,714 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:51:02,716 - websockets.server - INFO - connection closed
2024-06-05 19:52:49,415 - websockets.server - INFO - connection open
2024-06-05 19:52:49,416 - __main__ - INFO - Recibido: 6
2024-06-05 19:52:49,416 - __main__ - INFO - Iniciando la clase
2024-06-05 19:52:49,431 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:52:49,433 - websockets.server - INFO - connection closed
2024-06-05 19:53:47,522 - websockets.server - INFO - connection open
2024-06-05 19:53:47,525 - __main__ - INFO - Recibido: 6
2024-06-05 19:53:47,526 - __main__ - INFO - Iniciando la clase
2024-06-05 19:53:47,586 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:53:47,589 - websockets.server - INFO - connection closed
2024-06-05 19:54:17,326 - websockets.server - INFO - connection open
2024-06-05 19:54:17,331 - __main__ - INFO - Recibido: 6
2024-06-05 19:54:17,331 - __main__ - INFO - Iniciando la clase
2024-06-05 19:54:17,397 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:54:17,400 - websockets.server - INFO - connection closed
2024-06-05 19:56:18,212 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 19:56:18,212 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 19:56:18,212 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 19:56:26,026 - websockets.server - INFO - connection open
2024-06-05 19:56:26,028 - __main__ - INFO - Recibido: 1
2024-06-05 19:56:26,028 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:56:27,033 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:56:27,036 - websockets.server - INFO - connection closed
2024-06-05 19:56:32,830 - websockets.server - INFO - connection open
2024-06-05 19:56:32,832 - __main__ - INFO - Recibido: 2
2024-06-05 19:56:32,832 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-05 19:56:33,836 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:56:33,838 - websockets.server - INFO - connection closed
2024-06-05 19:56:38,732 - websockets.server - INFO - connection open
2024-06-05 19:56:38,733 - __main__ - INFO - Recibido: 1
2024-06-05 19:56:38,734 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 19:56:39,738 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:56:39,739 - websockets.server - INFO - connection closed
2024-06-05 19:57:32,344 - websockets.server - INFO - connection open
2024-06-05 19:57:32,346 - __main__ - INFO - Recibido: 6
2024-06-05 19:57:32,347 - __main__ - INFO - Iniciando la clase
2024-06-05 19:57:32,387 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:57:32,390 - websockets.server - INFO - connection closed
2024-06-05 19:58:20,846 - websockets.server - INFO - connection open
2024-06-05 19:58:20,848 - __main__ - INFO - Recibido: 6
2024-06-05 19:58:20,848 - __main__ - INFO - Iniciando la clase
2024-06-05 19:58:20,877 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 19:58:20,879 - websockets.server - INFO - connection closed
2024-06-05 20:00:23,051 - websockets.server - INFO - connection open
2024-06-05 20:00:23,054 - __main__ - INFO - Recibido: 6
2024-06-05 20:00:23,054 - __main__ - INFO - Iniciando la clase
2024-06-05 20:00:23,083 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:00:23,084 - websockets.server - INFO - connection closed
2024-06-05 20:00:38,251 - websockets.server - INFO - connection open
2024-06-05 20:00:38,252 - __main__ - INFO - Recibido: 7
2024-06-05 20:00:38,253 - __main__ - INFO - Finalizando la clase
2024-06-05 20:00:38,256 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:00:38,258 - websockets.server - INFO - connection closed
2024-06-05 20:01:12,031 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 20:01:12,031 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 20:01:12,031 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 20:01:25,964 - websockets.server - INFO - connection open
2024-06-05 20:01:25,966 - __main__ - INFO - Recibido: 6
2024-06-05 20:01:25,966 - __main__ - INFO - Iniciando la clase
2024-06-05 20:01:26,000 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:01:26,003 - websockets.server - INFO - connection closed
2024-06-05 20:02:11,963 - websockets.server - INFO - connection open
2024-06-05 20:02:11,965 - __main__ - INFO - Recibido: 6
2024-06-05 20:02:11,965 - __main__ - INFO - Iniciando la clase
2024-06-05 20:02:11,981 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:02:11,983 - websockets.server - INFO - connection closed
2024-06-05 20:05:41,369 - websockets.server - INFO - connection open
2024-06-05 20:05:41,370 - __main__ - INFO - Recibido: 6
2024-06-05 20:05:41,370 - __main__ - INFO - Iniciando la clase
2024-06-05 20:05:41,394 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:05:41,396 - websockets.server - INFO - connection closed
2024-06-05 20:06:50,773 - websockets.server - INFO - connection open
2024-06-05 20:06:50,775 - __main__ - INFO - Recibido: 6
2024-06-05 20:06:50,775 - __main__ - INFO - Iniciando la clase
2024-06-05 20:06:50,797 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:06:50,799 - websockets.server - INFO - connection closed
2024-06-05 20:07:04,878 - websockets.server - INFO - connection open
2024-06-05 20:07:04,879 - __main__ - INFO - Recibido: 1
2024-06-05 20:07:04,879 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 20:07:05,883 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:07:05,885 - websockets.server - INFO - connection closed
2024-06-05 20:25:41,192 - websockets.server - INFO - connection open
2024-06-05 20:25:41,196 - __main__ - INFO - Recibido: 6
2024-06-05 20:25:41,196 - __main__ - INFO - Iniciando la clase
2024-06-05 20:25:41,285 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:25:41,286 - websockets.server - INFO - connection closed
2024-06-05 20:29:05,598 - websockets.server - INFO - connection open
2024-06-05 20:29:05,602 - __main__ - INFO - Recibido: 6
2024-06-05 20:29:05,602 - __main__ - INFO - Iniciando la clase
2024-06-05 20:29:05,665 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:29:05,669 - websockets.server - INFO - connection closed
2024-06-05 20:29:26,496 - websockets.server - INFO - connection open
2024-06-05 20:29:26,498 - __main__ - INFO - Recibido: 6
2024-06-05 20:29:26,498 - __main__ - INFO - Iniciando la clase
2024-06-05 20:29:26,524 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:29:26,525 - websockets.server - INFO - connection closed
2024-06-05 20:29:40,315 - websockets.server - INFO - connection open
2024-06-05 20:29:40,317 - __main__ - INFO - Recibido: 6
2024-06-05 20:29:40,317 - __main__ - INFO - Iniciando la clase
2024-06-05 20:29:40,339 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:29:40,340 - websockets.server - INFO - connection closed
2024-06-05 20:35:48,492 - websockets.server - INFO - server listening on 127.0.0.1:8766
2024-06-05 20:35:48,492 - websockets.server - INFO - server listening on [::1]:8766
2024-06-05 20:35:48,492 - __main__ - INFO - Server started and listening on ws://localhost:8766
2024-06-05 20:36:56,412 - websockets.server - INFO - connection open
2024-06-05 20:36:56,413 - __main__ - INFO - Recibido: 6
2024-06-05 20:36:56,414 - __main__ - INFO - Iniciando la clase
2024-06-05 20:36:56,440 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:36:56,444 - websockets.server - INFO - connection closed
2024-06-05 20:37:00,413 - websockets.server - INFO - connection open
2024-06-05 20:37:00,415 - __main__ - INFO - Recibido: 1
2024-06-05 20:37:00,415 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-05 20:37:00,435 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 20:37:01,439 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:01,441 - websockets.server - INFO - connection closed
2024-06-05 20:37:04,017 - websockets.server - INFO - connection open
2024-06-05 20:37:04,019 - __main__ - INFO - Recibido: 2
2024-06-05 20:37:04,019 - __main__ - INFO - Moviendo servo a pizarra 2
2024-06-05 20:37:04,033 - __main__ - INFO - Ejecutando script de pizarra 2
2024-06-05 20:37:05,037 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:05,038 - websockets.server - INFO - connection closed
2024-06-05 20:37:10,023 - websockets.server - INFO - connection open
2024-06-05 20:37:10,025 - __main__ - INFO - Recibido: 3
2024-06-05 20:37:10,025 - __main__ - INFO - Se ha iniciado la grabacion
2024-06-05 20:37:10,044 - __main__ - INFO - Ejecutando script para empezar grabación
2024-06-05 20:37:10,049 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:10,051 - websockets.server - INFO - connection closed
2024-06-05 20:37:14,025 - websockets.server - INFO - connection open
2024-06-05 20:37:14,029 - __main__ - INFO - Recibido: 4
2024-06-05 20:37:14,030 - __main__ - INFO - Se ha detenido la grabacion
2024-06-05 20:37:14,053 - __main__ - INFO - Deteniendo la grabación
2024-06-05 20:37:14,060 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:14,062 - websockets.server - INFO - connection closed
2024-06-05 20:37:16,821 - websockets.server - INFO - connection open
2024-06-05 20:37:16,823 - __main__ - INFO - Recibido: 5
2024-06-05 20:37:16,823 - __main__ - INFO - Se ha tomado una foto
2024-06-05 20:37:16,848 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:16,849 - websockets.server - INFO - connection closed
2024-06-05 20:37:21,823 - websockets.server - INFO - connection open
2024-06-05 20:37:21,825 - __main__ - INFO - Recibido: 7
2024-06-05 20:37:21,825 - __main__ - INFO - Termina la clase
2024-06-05 20:37:21,839 - __main__ - INFO - Finalizando la clase
2024-06-05 20:37:21,843 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:21,845 - websockets.server - INFO - connection closed
2024-06-05 20:37:26,231 - websockets.server - INFO - connection open
2024-06-05 20:37:26,235 - __main__ - INFO - Recibido: 1
2024-06-05 20:37:26,235 - __main__ - INFO - Moviendo servo a pizarra 1
2024-06-05 20:37:26,261 - __main__ - INFO - Ejecutando script de pizarra 1
2024-06-05 20:37:27,267 - websockets.server - ERROR - connection handler failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/lib/python3/dist-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/opt/scripts/socket_cliente.py", line 17, in handle_client
    message = await websocket.recv()  # Espera un mensaje
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 953, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
2024-06-05 20:37:27,268 - websockets.server - INFO - connection closed
